/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffd9dd",
        "inverse-surface": "#353029",
        "inverse-on-surface": "#faefe5",
        "primary-fixed": "#d0e9d4",
        "on-surface-variant": "#434843",
        "tertiary-fixed": "#e0e5cc",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#0b2013",
        "background": "#fff8f3",
        "surface-container-low": "#fdf2e7",
        "on-primary-container": "#819986",
        "on-tertiary-container": "#90957f",
        "primary-fixed-dim": "#b4cdb8",
        "on-secondary-fixed": "#3d0413",
        "on-primary-fixed-variant": "#364c3c",
        "inverse-primary": "#b4cdb8",
        "on-secondary-fixed-variant": "#75303c",
        "surface-tint": "#4d6453",
        "on-tertiary": "#ffffff",
        "secondary-container": "#ffa1ae",
        "on-primary": "#ffffff",
        "on-surface": "#1f1b15",
        "on-error-container": "#93000a",
        "surface-dim": "#e2d8ce",
        "surface-container-high": "#f1e6dc",
        "secondary": "#924753",
        "on-tertiary-fixed-variant": "#444937",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c8c1",
        "surface-container-highest": "#ebe1d7",
        "surface": "#fff8f3",
        "tertiary-container": "#282d1d",
        "on-secondary-container": "#7b3440",
        "on-tertiary-fixed": "#191d0e",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary": "#061b0e",
        "outline": "#737973",
        "secondary-fixed-dim": "#ffb2bb",
        "tertiary": "#14190a",
        "surface-bright": "#fff8f3",
        "primary-container": "#1b3022",
        "surface-container": "#f7ece2",
        "tertiary-fixed-dim": "#c4c9b1",
        "surface-variant": "#ebe1d7",
        "on-background": "#1f1b15",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "16px",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Metropolis", "sans-serif"],
        "display-script": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Metropolis", "sans-serif"],
        "headline-md": ["Metropolis", "sans-serif"],
        "label-caps": ["Metropolis", "sans-serif"],
        "headline-sm": ["Metropolis", "sans-serif"],
        "headline-lg": ["Metropolis", "sans-serif"],
        "body-md": ["Metropolis", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-script": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
